domain: localhost:5000/ #domain that will be given to user. like domain.com/AsdnHJ. You CAN change it after use, server save only link code (AsdnHJ in example)
link_length: 5
check_unique: 1 #If true: server will check, if redirect is in database, and if it is, will give it's link