domain: localhost:5000/ #Domain, that will be given to user, when he will short link + link code.
link_length: 5  #Shorten link length
check_unique: 1 #If redirect link is in database, it won't create new